export interface Project {
  id: number;
  title: string;
  description: string;
  image: string;
  equipmentType: string;
  destination: string;
  containerType: string;
  weight: string;
  transitTime: string;
  category: string;
}

const projectsEn: Project[] = [
  // Row 1 — high-impact opening
  {
    id: 8,
    title: "John Deere Sprayer — Port Crane Loading",
    description: "We used a Contmaster reach stacker to crane-lift a John Deere self-propelled sprayer directly onto a flat rack at the container yard, threading the machine between stacked Maersk containers with less than a foot of clearance on each side. The 90-foot boom sections were removed and crated in custom wooden frames shipped alongside. The flat rack cleared St. Petersburg in 18 days with the buyer's customs broker pre-cleared for agricultural equipment import.",
    image: "/images/project-jd-sprayer-port-crane.jpg",
    equipmentType: "Self-Propelled Sprayer",
    destination: "St. Petersburg, Russia",
    containerType: "40ft Flat Rack",
    weight: "14,500 kg",
    transitTime: "18 days",
    category: "Spraying",
  },
  {
    id: 3,
    title: "Case IH 9120 Combine to Middle East",
    description: "We secured a Case IH 9120 combine and detached tires on a Hapag-Lloyd flat rack using custom wood blocking and grade-43 chain binders for overseas shipping to Saudi Arabia. At 18,000 kg, load distribution was critical — we calculated center of gravity and positioned the machine to stay within flat rack weight limits across all four corners. The shipment cleared Jeddah port in 30 days with all SABER documentation pre-approved.",
    image: "/images/project-case-ih-combine.jpg",
    equipmentType: "Combine Harvester",
    destination: "Jeddah, Saudi Arabia",
    containerType: "40ft Flat Rack",
    weight: "18,000 kg",
    transitTime: "30 days",
    category: "Harvesting",
  },
  // Row 2 — mixed container/flatrack
  {
    id: 4,
    title: "John Deere Combine Pair — Container Export",
    description: "We dismantled and packed two John Deere combines into side-by-side 40ft containers, loading rear-first with professional strapping to maximize space. Headers, augers, and GPS domes were removed and crated separately — every bolt bag was labeled for reassembly. The dual-container shipment reached Novorossiysk in 30 days, saving the buyer over $8,000 compared to flat rack pricing.",
    image: "/images/project-jd-tillage-containers.jpg",
    equipmentType: "Combine Harvesters",
    destination: "Novorossiysk, Russia",
    containerType: "2x 40ft Standard",
    weight: "22,000 kg",
    transitTime: "30 days",
    category: "Harvesting",
  },
  {
    id: 9,
    title: "John Deere 9650 STS — Oversized to Kazakhstan",
    description: "We transported a John Deere 9650 STS combine on an oversized lowboy trailer from Iowa to the loading port, with dual rear tires strapped alongside on the trailer deck. The header and unloading auger were removed, crated, and shipped in a separate 40ft container. The flat rack reached Aktau port after 42 days of transit via the Mediterranean and Caspian transshipment, with zero transport damage reported on arrival.",
    image: "/images/project-jd-9650sts-transport.jpg",
    equipmentType: "Combine Harvester",
    destination: "Aktau, Kazakhstan",
    containerType: "40ft Flat Rack",
    weight: "15,500 kg",
    transitTime: "42 days",
    category: "Harvesting",
  },
  {
    id: 6,
    title: "Shelbourne Stripper Headers",
    description: "We forklift-loaded Shelbourne stripper headers into two 40ft high-cube containers at our packing facility, adding custom protective bracing for the knife sections and belt assemblies. Each header was secured on welded transport stands to prevent lateral movement during 25 days of ocean transit to Constanta, Romania. The buyer confirmed all four units arrived in working condition.",
    image: "/images/project-shelbourne-loading.jpg",
    equipmentType: "Stripper Headers",
    destination: "Constanta, Romania",
    containerType: "2x 40ft HC",
    weight: "5,200 kg",
    transitTime: "25 days",
    category: "Harvesting",
  },
  // Row 3 — variety close
  {
    id: 10,
    title: "John Deere Combine Parts — Container Export",
    description: "We disassembled a John Deere combine into core components — cleaning fans, auger tubes, engine block, separator drums, and sieve assemblies — and consolidated everything into a single 40ft high-cube container. Each component was secured on pallets and custom welded frames to prevent shifting during 48 days of ocean and rail transit to Kostanay, Kazakhstan. The buyer confirmed all parts arrived intact for workshop reassembly.",
    image: "/images/project-spare-parts-container.jpg",
    equipmentType: "Combine Components",
    destination: "Kostanay, Kazakhstan",
    containerType: "40ft High Cube",
    weight: "19,000 kg",
    transitTime: "48 days",
    category: "Parts & Components",
  },
  {
    id: 2,
    title: "John Deere W260 Windrower Export",
    description: "We shipped a John Deere W260 windrower to the UAE on a Hapag-Lloyd flat rack with custom wood bracing and heavy-duty tie-downs at port. The draper header was crated separately to protect the belt and knife sections during 35 days of ocean transit. The buyer in Jebel Ali reported zero damage on arrival — equipment was operational within 48 hours.",
    image: "/images/project-jd-w260-windrower.jpg",
    equipmentType: "Windrower",
    destination: "Jebel Ali, UAE",
    containerType: "40ft Flat Rack",
    weight: "12,000 kg",
    transitTime: "35 days",
    category: "Harvesting",
  },
  {
    id: 7,
    title: "John Deere Self-Propelled Sprayer",
    description: "We crane-lifted a John Deere self-propelled sprayer onto a Maersk flat rack, crating the 120-foot boom sections separately in custom wooden frames for safe transit to Turkey. The chemical tank was triple-rinsed and certified clean for customs compliance. The sprayer arrived at Mersin port in 20 days and was reassembled by the buyer's team using our labeled documentation package.",
    image: "/images/project-jd-sprayer-crane.jpg",
    equipmentType: "Self-Propelled Sprayer",
    destination: "Mersin, Turkey",
    containerType: "40ft Flat Rack",
    weight: "14,000 kg",
    transitTime: "20 days",
    category: "Spraying",
  },
  // Row 4+ — new batch
  {
    id: 11,
    title: "Combine Loading — Aerial Drone View",
    description: "A bird's-eye drone shot captures a John Deere combine being loaded into a Hapag-Lloyd open-top container at our Albion, Iowa packing facility. The aerial perspective shows the precision required to position heavy equipment within the container walls — less than six inches of clearance on each side. This shipment traveled by rail to Chicago, then ocean to St. Petersburg, and finally rail to Kazan in 40 days.",
    image: "/images/project-jd-aerial-container.jpg",
    equipmentType: "Combine Harvester",
    destination: "Kazan, Tatarstan",
    containerType: "40ft Open Top",
    weight: "16,000 kg",
    transitTime: "40 days",
    category: "Harvesting",
  },
  {
    id: 12,
    title: "John Deere S670 Combine — Port Staging",
    description: "A John Deere S670 combine sits at the port yard in Savannah, GA awaiting flat rack placement. The header was removed and crated separately, and the unloading auger folded down for clearance. A port forklift stands ready for final positioning before lashing. The combine shipped to Le Havre on a Hapag-Lloyd flat rack and arrived in 16 days with zero damage — the buyer had it running within days of clearing French customs.",
    image: "/images/project-jd-s670-port.jpg",
    equipmentType: "Combine Harvester",
    destination: "Le Havre, France",
    containerType: "40ft Flat Rack",
    weight: "14,000 kg",
    transitTime: "16 days",
    category: "Harvesting",
  },
  {
    id: 13,
    title: "John Deere Sprayer — Container Loading",
    description: "We used an overhead crane to lower a John Deere self-propelled sprayer chassis-first into a 40ft high-cube container, captured here from ground level as the machine clears the container opening with inches to spare. The 90-foot boom sections were disassembled and crated alongside. The container shipped from Houston to Vladivostok via the Pacific route in 28 days, arriving in time for the Russian spring planting season.",
    image: "/images/project-jd-sprayer-container-load.jpg",
    equipmentType: "Self-Propelled Sprayer",
    destination: "Vladivostok, Russia",
    containerType: "40ft High Cube",
    weight: "13,500 kg",
    transitTime: "28 days",
    category: "Spraying",
  },
  {
    id: 14,
    title: "Shelbourne Reynolds Header — Container Loading",
    description: "A Shelbourne Reynolds CVS stripper header is guided into a 40ft container at our packing facility, the blue machine gleaming against the container wall. Custom wooden skids and ratchet straps secure the header for ocean transit. The shipment reached Odesa, Ukraine in 24 days, and the buyer integrated it with their existing John Deere combine fleet for the summer wheat harvest.",
    image: "/images/project-shelbourne-header-load.jpg",
    equipmentType: "Stripper Header",
    destination: "Odesa, Ukraine",
    containerType: "40ft Standard",
    weight: "4,800 kg",
    transitTime: "24 days",
    category: "Harvesting",
  },
  {
    id: 15,
    title: "Hagie Self-Propelled Sprayer — Flatbed Transport",
    description: "A Hagie STS self-propelled sprayer rides a step-deck trailer with its boom sections removed and crated in a custom wooden box marked for the buyer. The high-clearance sprayer was secured with heavy-duty chains and binders for the overland leg from Iowa to the Houston port. The flat rack reached Marseille in 18 days — the buyer reported the sprayer was field-ready within a week of customs clearance.",
    image: "/images/project-hagie-sprayer-flatbed.jpg",
    equipmentType: "Self-Propelled Sprayer",
    destination: "Marseille, France",
    containerType: "40ft Flat Rack",
    weight: "11,000 kg",
    transitTime: "18 days",
    category: "Spraying",
  },
  {
    id: 16,
    title: "Case IH Precision Air Cart — Port Crane",
    description: "A port crane lifts a Case IH Precision Air seeder cart onto a flat rack at the terminal, guided by a dockworker in full safety gear. The stainless-steel tank was cleaned and certified for agricultural import compliance. The shipment traveled from Baltimore through the Mediterranean to the Black Sea, reaching Rostov-on-Don in 30 days. The buyer paired it with a Bourgault drill for their fall planting campaign.",
    image: "/images/project-caseih-air-cart-crane.jpg",
    equipmentType: "Air Seeder Cart",
    destination: "Rostov-on-Don, Russia",
    containerType: "40ft Flat Rack",
    weight: "8,500 kg",
    transitTime: "30 days",
    category: "Planting",
  },
  {
    id: 17,
    title: "Kinze Planter — Flatbed Loading",
    description: "Workers secure a 16-row Kinze planter on a step-deck trailer at our facility, strapping each row unit to prevent shifting during the 800-mile haul to port. The seed hoppers and monitor cables were protected with custom covers. The planter shipped on a flat rack from Chicago to St. Petersburg, then by rail to Kazan, Tatarstan — total transit 42 days. The buyer had it calibrated and planting within two weeks of arrival.",
    image: "/images/project-kinze-planter-flatbed.jpg",
    equipmentType: "Row Planter",
    destination: "Kazan, Tatarstan",
    containerType: "40ft Flat Rack",
    weight: "7,200 kg",
    transitTime: "42 days",
    category: "Planting",
  },
  {
    id: 18,
    title: "John Deere Combine — Winter Pickup & Transport",
    description: "A K. Wheeler Transport lowboy picks up a John Deere combine in snowy Iowa conditions, with dual rear tires strapped to the headboard for the long haul to port. Winter pickups require extra prep — we pre-heated hydraulic lines and verified all fluids were winterized before loading. The combine reached Odesa, Ukraine in 25 days via the Mediterranean route, arriving just before the Black Sea spring thaw opened inland transport routes.",
    image: "/images/project-jd-combine-winter-transport.jpg",
    equipmentType: "Combine Harvester",
    destination: "Odesa, Ukraine",
    containerType: "40ft Flat Rack",
    weight: "15,000 kg",
    transitTime: "25 days",
    category: "Harvesting",
  },
  // Row 7+ — batch 3
  {
    id: 19,
    title: "John Deere 4044R Compact Tractor — Gooseneck Export",
    description: "We loaded a John Deere 4044R compact utility tractor with front-end loader onto a gooseneck trailer alongside a smaller JD zero-turn mower, strapping both units with heavy-duty ratchet binders. The package was consolidated at our Albion facility before shipping in a 40ft high-cube container — the tractor's ROPS was folded and the loader arms positioned for optimal space use. The shipment reached Almaty via Aktau port in 44 days.",
    image: "/images/project-jd-4044r-tractor.jpg",
    equipmentType: "Compact Tractor",
    destination: "Almaty, Kazakhstan",
    containerType: "40ft High Cube",
    weight: "2,400 kg",
    transitTime: "44 days",
    category: "Tractors",
  },
  {
    id: 20,
    title: "John Deere HydraFlex Header — Flatbed Transport",
    description: "A John Deere HydraFlex draper header rides a step-deck trailer toward the port, its cutterbar folded and the reel locked in travel position. Custom wooden cradles support the platform along its length to prevent frame flex during transit. The header shipped to Santiago, Chile on a flat rack via the Panama Canal route in 32 days — one of our first Chilean wheat-country deliveries.",
    image: "/images/project-jd-hydraflex-header.jpg",
    equipmentType: "HydraFlex Header",
    destination: "Santiago, Chile",
    containerType: "40ft Flat Rack",
    weight: "3,800 kg",
    transitTime: "32 days",
    category: "Harvesting",
  },
  {
    id: 21,
    title: "Shelbourne Headers on Meridian Freight Trailer",
    description: "Multiple Shelbourne Reynolds stripper headers ride our branded Meridian Freight gooseneck trailer at our Iowa facility, ready for the long haul to port. Our in-house fleet handles the critical first mile — we load, strap, and transport equipment ourselves instead of trusting third-party carriers for the most damage-prone leg. The headers shipped to Bishkek via Novorossiysk and overland rail in 38 days.",
    image: "/images/project-shelbourne-meridian-trailer.jpg",
    equipmentType: "Stripper Headers",
    destination: "Bishkek, Kyrgyzstan",
    containerType: "2x 40ft HC",
    weight: "5,600 kg",
    transitTime: "38 days",
    category: "Harvesting",
  },
  {
    id: 22,
    title: "John Deere 925F Header — Forklift Loading",
    description: "A Toyota forklift guides a John Deere 925F rigid platform header onto a step-deck trailer at our packing facility, with workers directing the operator for precise placement. The header's pickup reel was retracted and the dividers removed to minimize width. The shipment reached Mykolaiv, Ukraine on a flat rack in 26 days via the Mediterranean route, arriving in time for the winter wheat harvest.",
    image: "/images/project-jd-925f-header-load.jpg",
    equipmentType: "Rigid Platform Header",
    destination: "Mykolaiv, Ukraine",
    containerType: "40ft Flat Rack",
    weight: "2,900 kg",
    transitTime: "26 days",
    category: "Harvesting",
  },
  {
    id: 23,
    title: "Shelbourne Header — Container Loading",
    description: "A Shelbourne Reynolds stripper header is forklift-guided into a 40ft high-cube container at our facility, the blue machine threading through the container opening with mere inches of clearance on each side. Behind it, another flat rack stands ready for the next load. The shipment reached Krasnodar, Russia in 34 days via Novorossiysk port, with the buyer integrating it into their wheat harvest operations within a week.",
    image: "/images/project-shelbourne-container-load.jpg",
    equipmentType: "Stripper Header",
    destination: "Krasnodar, Russia",
    containerType: "40ft High Cube",
    weight: "2,700 kg",
    transitTime: "34 days",
    category: "Harvesting",
  },
  {
    id: 24,
    title: "MacDon D65 Draper Header — Gooseneck Transport",
    description: "A MacDon D65 draper header rides a gooseneck trailer through overcast skies toward the port, its pickup reel teeth silhouetted against the clouds. The polyethylene skid plates were wrapped in protective film to prevent shipping abrasion. The shipment traveled via Houston to Aktau and then overland rail to Shymkent, reaching the buyer in 46 days — the MacDon is prized among Kazakh grain growers for its clean cut in wheat and barley.",
    image: "/images/project-macdon-d65-draper.jpg",
    equipmentType: "Draper Header",
    destination: "Shymkent, Kazakhstan",
    containerType: "40ft Flat Rack",
    weight: "3,400 kg",
    transitTime: "46 days",
    category: "Harvesting",
  },
  {
    id: 25,
    title: "Kinze Planter — Winter Pickup & Transport",
    description: "A Kinze 3600 16-row planter is towed on its own transport wheels through snowy Iowa fields for the long haul to port. Winter pickups require extra care — we verified seed meters were emptied, drive chains lubricated, and the row units locked against impact. The planter shipped from Chicago via Novorossiysk and overland rail to Bishkek in 41 days, arriving in time for the buyer's spring soybean planting.",
    image: "/images/project-kinze-winter-transport.jpg",
    equipmentType: "Row Planter",
    destination: "Bishkek, Kyrgyzstan",
    containerType: "40ft Flat Rack",
    weight: "6,800 kg",
    transitTime: "41 days",
    category: "Planting",
  },
];

// ES: Projects with LATAM destinations first
const projectsEs: Project[] = [
  {
    id: 8,
    title: "Pulverizadora John Deere — Carga con Grúa en Puerto",
    description: "Utilizamos un reach stacker Contmaster para elevar con grúa una pulverizadora autopropulsada John Deere directamente sobre un flat rack en el patio de contenedores, pasando la máquina entre contenedores Maersk apilados con menos de 30 cm de espacio a cada lado. Las secciones de barra de 27 metros se retiraron y embalaron en marcos de madera a medida. El flat rack pasó la aduana de San Petersburgo en 18 días con el agente aduanero del comprador preaprobado para importación de equipos agrícolas.",
    image: "/images/project-jd-sprayer-port-crane.jpg",
    equipmentType: "Pulverizadora Autopropulsada",
    destination: "San Petersburgo, Rusia",
    containerType: "40ft Flat Rack",
    weight: "14,500 kg",
    transitTime: "18 días",
    category: "Pulverización",
  },
  {
    id: 3,
    title: "Cosechadora Case IH 9120 a Medio Oriente",
    description: "Aseguramos una cosechadora Case IH 9120 y llantas desmontadas en un flat rack Hapag-Lloyd usando bloqueo de madera a medida y tensores de cadena grado 43 para envío a Arabia Saudita. Con 18,000 kg, la distribución de carga fue crítica — calculamos el centro de gravedad y posicionamos la máquina para mantenerse dentro de los límites de peso del flat rack en las cuatro esquinas. El envío pasó la aduana de Jeddah en 30 días con toda la documentación SABER preaprobada.",
    image: "/images/project-case-ih-combine.jpg",
    equipmentType: "Cosechadora",
    destination: "Jeddah, Arabia Saudita",
    containerType: "40ft Flat Rack",
    weight: "18,000 kg",
    transitTime: "30 días",
    category: "Cosecha",
  },
  {
    id: 4,
    title: "Par de Cosechadoras John Deere — Exportación en Contenedor",
    description: "Desmontamos y empacamos dos cosechadoras John Deere en contenedores de 40ft lado a lado, cargando por la parte trasera con cintas profesionales para maximizar el espacio. Los cabezales, descargas y domos GPS se retiraron y embalaron por separado — cada bolsa de tornillería se etiquetó para reensamblaje. El envío de doble contenedor llegó a Novorossiysk en 30 días, ahorrando al comprador más de $8,000 comparado con precios de flat rack.",
    image: "/images/project-jd-tillage-containers.jpg",
    equipmentType: "Cosechadoras",
    destination: "Novorossiysk, Rusia",
    containerType: "2x 40ft Estándar",
    weight: "22,000 kg",
    transitTime: "30 días",
    category: "Cosecha",
  },
  {
    id: 9,
    title: "John Deere 9650 STS — Sobredimensionado a Kazajistán",
    description: "Transportamos una cosechadora John Deere 9650 STS en un tráiler lowboy sobredimensionado desde Iowa hasta el puerto de carga, con neumáticos traseros dobles asegurados junto a ella en la plataforma. El cabezal y la descarga se retiraron, embalaron y enviaron en un contenedor de 40ft separado. El flat rack llegó al puerto de Aktau después de 42 días de tránsito por el Mediterráneo y transbordo al Mar Caspio, sin daños de transporte reportados.",
    image: "/images/project-jd-9650sts-transport.jpg",
    equipmentType: "Cosechadora",
    destination: "Aktau, Kazajistán",
    containerType: "40ft Flat Rack",
    weight: "15,500 kg",
    transitTime: "42 días",
    category: "Cosecha",
  },
  {
    id: 6,
    title: "Cabezales Stripper Shelbourne",
    description: "Cargamos con montacargas cabezales stripper Shelbourne en dos contenedores 40ft high-cube en nuestra instalación de embalaje, añadiendo arriostrado protector a medida para las secciones de cuchilla y ensamblajes de banda. Cada cabezal se aseguró en soportes de transporte soldados para prevenir movimiento lateral durante 25 días de tránsito marítimo a Constanta, Rumania. El comprador confirmó que las cuatro unidades llegaron en condición de funcionamiento.",
    image: "/images/project-shelbourne-loading.jpg",
    equipmentType: "Cabezales Stripper",
    destination: "Constanta, Rumania",
    containerType: "2x 40ft HC",
    weight: "5,200 kg",
    transitTime: "25 días",
    category: "Cosecha",
  },
  {
    id: 10,
    title: "Repuestos de Cosechadora John Deere — Contenedor",
    description: "Desmontamos una cosechadora John Deere en sus componentes principales — ventiladores de limpieza, tubos de descarga, bloque motor, tambores separadores y ensamblajes de cribas — y consolidamos todo en un contenedor 40ft high-cube. Cada componente se aseguró en paletas y marcos soldados a medida para prevenir desplazamiento durante 48 días de tránsito marítimo y ferroviario hasta Kostanay, Kazajistán. El comprador confirmó que todas las piezas llegaron intactas para reensamblaje en taller.",
    image: "/images/project-spare-parts-container.jpg",
    equipmentType: "Componentes de Cosechadora",
    destination: "Kostanay, Kazajistán",
    containerType: "40ft High Cube",
    weight: "19,000 kg",
    transitTime: "48 días",
    category: "Repuestos",
  },
  {
    id: 2,
    title: "Exportación de Segadora John Deere W260",
    description: "Enviamos una segadora John Deere W260 a los EAU en un flat rack Hapag-Lloyd con arriostrado de madera a medida y amarres de servicio pesado en puerto. El cabezal draper se embaló por separado en caja para proteger las secciones de banda y cuchilla durante 35 días de tránsito marítimo. El comprador en Jebel Ali reportó cero daños a la llegada — el equipo estuvo operativo en 48 horas.",
    image: "/images/project-jd-w260-windrower.jpg",
    equipmentType: "Segadora",
    destination: "Jebel Ali, EAU",
    containerType: "40ft Flat Rack",
    weight: "12,000 kg",
    transitTime: "35 días",
    category: "Cosecha",
  },
  {
    id: 7,
    title: "Pulverizadora Autopropulsada John Deere",
    description: "Elevamos con grúa una pulverizadora autopropulsada John Deere sobre un flat rack Maersk, embalando las secciones de barra de 36 metros por separado en marcos de madera a medida para un tránsito seguro a Turquía. El tanque de químicos se enjuagó tres veces y se certificó limpio para cumplimiento aduanero. La pulverizadora llegó al puerto de Mersin en 20 días y fue reensamblada por el equipo del comprador usando nuestro paquete de documentación etiquetada.",
    image: "/images/project-jd-sprayer-crane.jpg",
    equipmentType: "Pulverizadora Autopropulsada",
    destination: "Mersin, Turquía",
    containerType: "40ft Flat Rack",
    weight: "14,000 kg",
    transitTime: "20 días",
    category: "Pulverización",
  },
  {
    id: 11,
    title: "Carga de Cosechadora — Vista Aérea con Dron",
    description: "Una toma aérea con dron captura una cosechadora John Deere siendo cargada en un contenedor open-top Hapag-Lloyd en nuestra instalación de embalaje en Albion, Iowa. La perspectiva aérea muestra la precisión requerida para posicionar equipo pesado dentro de las paredes del contenedor — menos de 15 cm de espacio a cada lado. Este envío viajó por ferrocarril a Chicago, luego por mar a San Petersburgo, y finalmente por tren a Kazán en 40 días.",
    image: "/images/project-jd-aerial-container.jpg",
    equipmentType: "Cosechadora",
    destination: "Kazán, Tartaristán",
    containerType: "40ft Open Top",
    weight: "16,000 kg",
    transitTime: "40 días",
    category: "Cosecha",
  },
  {
    id: 12,
    title: "Cosechadora John Deere S670 — Estacionamiento en Puerto",
    description: "Una cosechadora John Deere S670 espera en el patio portuario de Savannah, GA para ser colocada en un flat rack. El cabezal fue retirado y embalado por separado, y la descarga plegada para dar altura libre. Un montacargas portuario está listo para el posicionamiento final antes del amarre. La cosechadora se envió a Le Havre en un flat rack Hapag-Lloyd y llegó en 16 días sin daños.",
    image: "/images/project-jd-s670-port.jpg",
    equipmentType: "Cosechadora",
    destination: "Le Havre, Francia",
    containerType: "40ft Flat Rack",
    weight: "14,000 kg",
    transitTime: "16 días",
    category: "Cosecha",
  },
  {
    id: 13,
    title: "Pulverizadora John Deere — Carga en Contenedor",
    description: "Utilizamos una grúa aérea para bajar el chasis de una pulverizadora autopropulsada John Deere dentro de un contenedor 40ft high-cube, capturada aquí desde nivel del suelo cuando la máquina pasa por la apertura del contenedor con centímetros de margen. Las secciones de barra de 27 metros fueron desarmadas y embaladas por separado. El contenedor se envió de Houston a Vladivostok por la ruta del Pacífico en 28 días.",
    image: "/images/project-jd-sprayer-container-load.jpg",
    equipmentType: "Pulverizadora Autopropulsada",
    destination: "Vladivostok, Rusia",
    containerType: "40ft High Cube",
    weight: "13,500 kg",
    transitTime: "28 días",
    category: "Pulverización",
  },
  {
    id: 14,
    title: "Cabezal Shelbourne Reynolds — Carga en Contenedor",
    description: "Un cabezal stripper Shelbourne Reynolds CVS es guiado dentro de un contenedor de 40ft en nuestra instalación de embalaje, la máquina azul brillando contra la pared del contenedor. Patines de madera a medida y cintas de trinquete aseguran el cabezal para el tránsito marítimo. El envío llegó a Odesa, Ucrania en 24 días, y el comprador lo integró con su flota existente de cosechadoras John Deere.",
    image: "/images/project-shelbourne-header-load.jpg",
    equipmentType: "Cabezal Stripper",
    destination: "Odesa, Ucrania",
    containerType: "40ft Estándar",
    weight: "4,800 kg",
    transitTime: "24 días",
    category: "Cosecha",
  },
  {
    id: 15,
    title: "Pulverizadora Hagie — Transporte en Plataforma",
    description: "Una pulverizadora autopropulsada Hagie STS viaja en un tráiler de plataforma escalonada con sus secciones de barra removidas y embaladas en una caja de madera a medida marcada para el comprador. La pulverizadora de alta despejamiento fue asegurada con cadenas pesadas y tensores para el tramo terrestre desde Iowa hasta el puerto de Houston. El flat rack llegó a Marsella en 18 días.",
    image: "/images/project-hagie-sprayer-flatbed.jpg",
    equipmentType: "Pulverizadora Autopropulsada",
    destination: "Marsella, Francia",
    containerType: "40ft Flat Rack",
    weight: "11,000 kg",
    transitTime: "18 días",
    category: "Pulverización",
  },
  {
    id: 16,
    title: "Carro Case IH Precision Air — Grúa Portuaria",
    description: "Una grúa portuaria eleva un carro sembrador Case IH Precision Air sobre un flat rack en la terminal, guiado por un estibador con equipo de seguridad completo. El tanque de acero inoxidable fue limpiado y certificado para cumplimiento de importación agrícola. El envío viajó desde Baltimore por el Mediterráneo hasta el Mar Negro, llegando a Rostov del Don en 30 días.",
    image: "/images/project-caseih-air-cart-crane.jpg",
    equipmentType: "Carro Sembrador",
    destination: "Rostov del Don, Rusia",
    containerType: "40ft Flat Rack",
    weight: "8,500 kg",
    transitTime: "30 días",
    category: "Siembra",
  },
  {
    id: 17,
    title: "Sembradora Kinze — Carga en Plataforma",
    description: "Trabajadores aseguran una sembradora Kinze de 16 hileras en un tráiler de plataforma escalonada en nuestra instalación, sujetando cada unidad de hilera para prevenir desplazamiento durante el traslado de 1,300 km hasta el puerto. Las tolvas de semilla y cables del monitor fueron protegidos con cubiertas a medida. La sembradora se envió en flat rack de Chicago a San Petersburgo, luego por tren a Kazán — tránsito total de 42 días.",
    image: "/images/project-kinze-planter-flatbed.jpg",
    equipmentType: "Sembradora de Hileras",
    destination: "Kazán, Tartaristán",
    containerType: "40ft Flat Rack",
    weight: "7,200 kg",
    transitTime: "42 días",
    category: "Siembra",
  },
  {
    id: 18,
    title: "Cosechadora John Deere — Recolección y Transporte Invernal",
    description: "Un lowboy de K. Wheeler Transport recoge una cosechadora John Deere en condiciones nevadas de Iowa, con neumáticos traseros dobles asegurados en la cabecera para el largo traslado al puerto. Las recolecciones invernales requieren preparación extra — precalentamos las líneas hidráulicas y verificamos que todos los fluidos estuvieran invernizados antes de cargar. La cosechadora llegó a Odesa, Ucrania en 25 días por la ruta del Mediterráneo.",
    image: "/images/project-jd-combine-winter-transport.jpg",
    equipmentType: "Cosechadora",
    destination: "Odesa, Ucrania",
    containerType: "40ft Flat Rack",
    weight: "15,000 kg",
    transitTime: "25 días",
    category: "Cosecha",
  },
  {
    id: 20,
    title: "Cabezal John Deere HydraFlex — Transporte en Plataforma",
    description: "Un cabezal draper John Deere HydraFlex viaja en un tráiler de plataforma escalonada hacia el puerto, con su barra de corte plegada y el molinete bloqueado en posición de transporte. Cunas de madera a medida soportan la plataforma a lo largo de su longitud para evitar flexión del marco durante el tránsito. El cabezal se envió a Santiago, Chile en un flat rack por la ruta del Canal de Panamá en 32 días — una de nuestras primeras entregas al país trigero chileno.",
    image: "/images/project-jd-hydraflex-header.jpg",
    equipmentType: "Cabezal HydraFlex",
    destination: "Santiago, Chile",
    containerType: "40ft Flat Rack",
    weight: "3,800 kg",
    transitTime: "32 días",
    category: "Cosecha",
  },
  {
    id: 19,
    title: "Tractor Compacto John Deere 4044R — Exportación en Gooseneck",
    description: "Cargamos un tractor utilitario compacto John Deere 4044R con cargador frontal en un tráiler gooseneck junto con una podadora JD zero-turn más pequeña, asegurando ambas unidades con tensores pesados de trinquete. El paquete se consolidó en nuestra instalación de Albion antes del envío en un contenedor de 40ft high-cube. El envío llegó a Almaty vía puerto de Aktau en 44 días.",
    image: "/images/project-jd-4044r-tractor.jpg",
    equipmentType: "Tractor Compacto",
    destination: "Almaty, Kazajistán",
    containerType: "40ft High Cube",
    weight: "2,400 kg",
    transitTime: "44 días",
    category: "Tractores",
  },
  {
    id: 21,
    title: "Cabezales Shelbourne en Remolque Meridian Freight",
    description: "Múltiples cabezales stripper Shelbourne Reynolds viajan en nuestro remolque gooseneck Meridian Freight con nuestra marca en Iowa, listos para el largo traslado al puerto. Nuestra flota interna maneja la primera milla crítica — cargamos, amarramos y transportamos equipos nosotros mismos en lugar de confiar en transportistas externos. Los cabezales se enviaron a Biskek vía Novorossiysk y transporte ferroviario en 38 días.",
    image: "/images/project-shelbourne-meridian-trailer.jpg",
    equipmentType: "Cabezales Stripper",
    destination: "Biskek, Kirguistán",
    containerType: "2x 40ft HC",
    weight: "5,600 kg",
    transitTime: "38 días",
    category: "Cosecha",
  },
  {
    id: 22,
    title: "Cabezal John Deere 925F — Carga con Montacargas",
    description: "Un montacargas Toyota guía un cabezal de plataforma rígida John Deere 925F sobre un tráiler de plataforma en nuestra instalación de embalaje, con trabajadores dirigiendo al operador para una colocación precisa. El molinete del cabezal fue retraído y los divisores removidos para minimizar el ancho. El envío llegó a Mykolaiv, Ucrania en un flat rack en 26 días por la ruta del Mediterráneo.",
    image: "/images/project-jd-925f-header-load.jpg",
    equipmentType: "Cabezal Plataforma Rígida",
    destination: "Mykolaiv, Ucrania",
    containerType: "40ft Flat Rack",
    weight: "2,900 kg",
    transitTime: "26 días",
    category: "Cosecha",
  },
  {
    id: 23,
    title: "Cabezal Shelbourne — Carga en Contenedor",
    description: "Un cabezal stripper Shelbourne Reynolds es guiado con montacargas dentro de un contenedor 40ft high-cube en nuestra instalación, la máquina azul pasando por la apertura del contenedor con apenas centímetros de espacio a cada lado. Detrás, otro flat rack espera la próxima carga. El envío llegó a Krasnodar, Rusia en 34 días vía puerto de Novorossiysk.",
    image: "/images/project-shelbourne-container-load.jpg",
    equipmentType: "Cabezal Stripper",
    destination: "Krasnodar, Rusia",
    containerType: "40ft High Cube",
    weight: "2,700 kg",
    transitTime: "34 días",
    category: "Cosecha",
  },
  {
    id: 24,
    title: "Cabezal Draper MacDon D65 — Transporte Gooseneck",
    description: "Un cabezal draper MacDon D65 viaja en un tráiler gooseneck bajo cielos nublados hacia el puerto, con los dientes de su molinete recogedor silueteados contra las nubes. Las placas de deslizamiento de polietileno fueron envueltas en película protectora para evitar abrasión durante el envío. El envío viajó vía Houston a Aktau y luego por tren terrestre a Shymkent, llegando al comprador en 46 días.",
    image: "/images/project-macdon-d65-draper.jpg",
    equipmentType: "Cabezal Draper",
    destination: "Shymkent, Kazajistán",
    containerType: "40ft Flat Rack",
    weight: "3,400 kg",
    transitTime: "46 días",
    category: "Cosecha",
  },
  {
    id: 25,
    title: "Sembradora Kinze — Recolección y Transporte Invernal",
    description: "Una sembradora Kinze 3600 de 16 hileras es remolcada sobre sus propias ruedas de transporte a través de campos nevados de Iowa para el largo traslado al puerto. Las recolecciones invernales requieren cuidado extra — verificamos que los medidores de semillas estuvieran vacíos, las cadenas de transmisión lubricadas y las unidades de hilera bloqueadas contra impacto. La sembradora se envió desde Chicago vía Novorossiysk y transporte ferroviario a Biskek en 41 días.",
    image: "/images/project-kinze-winter-transport.jpg",
    equipmentType: "Sembradora de Hileras",
    destination: "Biskek, Kirguistán",
    containerType: "40ft Flat Rack",
    weight: "6,800 kg",
    transitTime: "41 días",
    category: "Siembra",
  },
];

// RU: Projects with CIS destinations first
const projectsRu: Project[] = [
  {
    id: 4,
    title: "Пара комбайнов John Deere — контейнерный экспорт",
    description: "Мы разобрали и упаковали два комбайна John Deere в два 40-футовых контейнера, загружая задней частью с профессиональной обвязкой для максимизации пространства. Жатки, шнеки и GPS-антенны были сняты и упакованы отдельно — каждый пакет с крепежом промаркирован для сборки. Сдвоенная контейнерная отправка достигла Новороссийска за 30 дней, сэкономив покупателю более $8 000 по сравнению с тарифами на flat rack.",
    image: "/images/project-jd-tillage-containers.jpg",
    equipmentType: "Зерноуборочные комбайны",
    destination: "Новороссийск, Россия",
    containerType: "2x 40 футов Стандарт",
    weight: "22 000 кг",
    transitTime: "30 дней",
    category: "Уборка",
  },
  {
    id: 8,
    title: "Опрыскиватель John Deere — погрузка краном в порту",
    description: "Мы использовали ричстакер Contmaster для подъёма самоходного опрыскивателя John Deere непосредственно на flat rack в контейнерном терминале, проведя машину между штабелями контейнеров Maersk с зазором менее 30 см с каждой стороны. Секции штанги длиной 27 метров были сняты и упакованы в деревянные рамы на заказ. Flat rack прошёл таможню Санкт-Петербурга за 18 дней, таможенный брокер покупателя был заранее согласован на импорт сельхозтехники.",
    image: "/images/project-jd-sprayer-port-crane.jpg",
    equipmentType: "Самоходный опрыскиватель",
    destination: "Санкт-Петербург, Россия",
    containerType: "40 футов Flat Rack",
    weight: "14 500 кг",
    transitTime: "18 дней",
    category: "Опрыскивание",
  },
  {
    id: 9,
    title: "John Deere 9650 STS — негабарит в Казахстан",
    description: "Мы перевезли комбайн John Deere 9650 STS на негабаритном трале из Айовы до порта погрузки, закрепив сдвоенные задние колёса рядом на платформе трала. Жатка и выгрузной шнек были сняты, упакованы и отправлены в отдельном 40-футовом контейнере. Flat rack достиг порта Актау через 42 дня транзита через Средиземное море с перевалкой на Каспий — покупатель подтвердил отсутствие повреждений при приёмке.",
    image: "/images/project-jd-9650sts-transport.jpg",
    equipmentType: "Зерноуборочный комбайн",
    destination: "Актау, Казахстан",
    containerType: "40 футов Flat Rack",
    weight: "15 500 кг",
    transitTime: "42 дня",
    category: "Уборка",
  },
  {
    id: 10,
    title: "Запчасти комбайна John Deere — контейнерный экспорт",
    description: "Мы разобрали комбайн John Deere на основные узлы — вентиляторы очистки, шнековые трубы, блок двигателя, барабаны сепаратора и решётные станы — и консолидировали всё в один 40-футовый контейнер high-cube. Каждый компонент был закреплён на поддонах и сварных рамах на заказ для предотвращения смещения в течение 48 дней морского и железнодорожного транзита до Костаная, Казахстан. Покупатель подтвердил, что все детали прибыли в целости для сборки в мастерской.",
    image: "/images/project-spare-parts-container.jpg",
    equipmentType: "Комплектующие комбайна",
    destination: "Костанай, Казахстан",
    containerType: "40 футов High Cube",
    weight: "19 000 кг",
    transitTime: "48 дней",
    category: "Запчасти",
  },
  {
    id: 6,
    title: "Очёсывающие жатки Shelbourne",
    description: "Мы загрузили погрузчиком очёсывающие жатки Shelbourne в два 40-футовых контейнера high-cube на нашем упаковочном предприятии, добавив защитное раскрепление для ножевых секций и ленточных узлов. Каждая жатка была закреплена на сварных транспортных стойках для предотвращения бокового смещения во время 25 дней морского транзита до Констанцы, Румыния. Покупатель подтвердил, что все четыре единицы прибыли в рабочем состоянии.",
    image: "/images/project-shelbourne-loading.jpg",
    equipmentType: "Очёсывающие жатки",
    destination: "Констанца, Румыния",
    containerType: "2x 40 футов HC",
    weight: "5 200 кг",
    transitTime: "25 дней",
    category: "Уборка",
  },
  {
    id: 7,
    title: "Самоходный опрыскиватель John Deere",
    description: "Мы подняли краном самоходный опрыскиватель John Deere на flat rack Maersk, упаковав 36-метровые секции штанги отдельно в деревянных рамах на заказ для безопасного транзита в Турцию. Химический бак был трижды промыт и сертифицирован как чистый для таможенного соответствия. Опрыскиватель прибыл в порт Мерсин за 20 дней и был собран командой покупателя с использованием нашего маркированного пакета документации.",
    image: "/images/project-jd-sprayer-crane.jpg",
    equipmentType: "Самоходный опрыскиватель",
    destination: "Мерсин, Турция",
    containerType: "40 футов Flat Rack",
    weight: "14 000 кг",
    transitTime: "20 дней",
    category: "Опрыскивание",
  },
  {
    id: 2,
    title: "Экспорт валковой жатки John Deere W260",
    description: "Мы отправили валковую жатку John Deere W260 в ОАЭ на flat rack Hapag-Lloyd с деревянным раскреплением на заказ и тяжёлыми стяжками в порту. Жатка draper была упакована отдельно для защиты ленты и ножевых секций во время 35 дней морского транзита. Покупатель в Джебель-Али сообщил об отсутствии повреждений при прибытии — техника была введена в эксплуатацию в течение 48 часов.",
    image: "/images/project-jd-w260-windrower.jpg",
    equipmentType: "Валковая жатка",
    destination: "Джебель-Али, ОАЭ",
    containerType: "40 футов Flat Rack",
    weight: "12 000 кг",
    transitTime: "35 дней",
    category: "Уборка",
  },
  {
    id: 3,
    title: "Комбайн Case IH 9120 на Ближний Восток",
    description: "Мы закрепили комбайн Case IH 9120 и снятые шины на flat rack Hapag-Lloyd, используя деревянное блокирование на заказ и цепные стяжки класса 43 для отправки в Саудовскую Аравию. При весе 18 000 кг распределение нагрузки было критичным — мы рассчитали центр тяжести и позиционировали машину для соблюдения предельных нагрузок на угловые стойки flat rack. Груз прошёл таможню порта Джидда за 30 дней с предварительно утверждённой документацией SABER.",
    image: "/images/project-case-ih-combine.jpg",
    equipmentType: "Зерноуборочный комбайн",
    destination: "Джидда, Саудовская Аравия",
    containerType: "40 футов Flat Rack",
    weight: "18 000 кг",
    transitTime: "30 дней",
    category: "Уборка",
  },
  {
    id: 11,
    title: "Погрузка комбайна — аэросъёмка с дрона",
    description: "Вид с дрона запечатлел погрузку комбайна John Deere в контейнер open-top Hapag-Lloyd на нашей упаковочной базе в Албион, Айова. Аэроперспектива показывает точность, необходимую для позиционирования тяжёлой техники внутри стенок контейнера — менее 15 см зазора с каждой стороны. Этот груз проследовал по железной дороге до Чикаго, затем морем до Санкт-Петербурга и далее поездом до Казани за 40 дней.",
    image: "/images/project-jd-aerial-container.jpg",
    equipmentType: "Зерноуборочный комбайн",
    destination: "Казань, Татарстан",
    containerType: "40 футов Open Top",
    weight: "16 000 кг",
    transitTime: "40 дней",
    category: "Уборка",
  },
  {
    id: 13,
    title: "Опрыскиватель John Deere — погрузка в контейнер",
    description: "Мы использовали мостовой кран для опускания шасси самоходного опрыскивателя John Deere в 40-футовый контейнер high-cube — здесь машина проходит через проём контейнера с зазором в считанные сантиметры. Секции штанги длиной 27 метров были разобраны и упакованы отдельно. Контейнер был отправлен из Хьюстона во Владивосток тихоокеанским маршрутом за 28 дней, прибыв к началу весеннего сезона опрыскивания.",
    image: "/images/project-jd-sprayer-container-load.jpg",
    equipmentType: "Самоходный опрыскиватель",
    destination: "Владивосток, Россия",
    containerType: "40 футов High Cube",
    weight: "13 500 кг",
    transitTime: "28 дней",
    category: "Опрыскивание",
  },
  {
    id: 16,
    title: "Пневматический посевной бункер Case IH — портовый кран",
    description: "Портовый кран поднимает пневматический посевной бункер Case IH Precision Air на flat rack в терминале под руководством докера в полной экипировке. Бак из нержавеющей стали был очищен и сертифицирован для импорта сельхозтехники. Груз проследовал из Балтимора через Средиземное море в Чёрное, достигнув Ростова-на-Дону за 30 дней. Покупатель агрегатировал его с сеялкой Bourgault для осенней посевной.",
    image: "/images/project-caseih-air-cart-crane.jpg",
    equipmentType: "Посевной бункер",
    destination: "Ростов-на-Дону, Россия",
    containerType: "40 футов Flat Rack",
    weight: "8 500 кг",
    transitTime: "30 дней",
    category: "Посев",
  },
  {
    id: 17,
    title: "Сеялка Kinze — погрузка на платформу",
    description: "Рабочие закрепляют 16-рядную сеялку Kinze на низкорамном трале на нашей базе, фиксируя каждый посевной секцию для предотвращения смещения при перевозке на 1 300 км до порта. Семенные бункеры и кабели монитора были защищены чехлами на заказ. Сеялка отправлена на flat rack из Чикаго в Санкт-Петербург, далее по железной дороге до Казани — общий транзит 42 дня.",
    image: "/images/project-kinze-planter-flatbed.jpg",
    equipmentType: "Рядковая сеялка",
    destination: "Казань, Татарстан",
    containerType: "40 футов Flat Rack",
    weight: "7 200 кг",
    transitTime: "42 дня",
    category: "Посев",
  },
  {
    id: 18,
    title: "Комбайн John Deere — зимний вывоз и транспортировка",
    description: "Трал K. Wheeler Transport забирает комбайн John Deere в зимних условиях Айовы, с задними сдвоенными колёсами, закреплёнными на стойке для дальней перевозки в порт. Зимний вывоз требует дополнительной подготовки — мы прогрели гидролинии и проверили зимнюю подготовку всех жидкостей перед погрузкой. Комбайн достиг Одессы, Украина за 25 дней средиземноморским маршрутом.",
    image: "/images/project-jd-combine-winter-transport.jpg",
    equipmentType: "Зерноуборочный комбайн",
    destination: "Одесса, Украина",
    containerType: "40 футов Flat Rack",
    weight: "15 000 кг",
    transitTime: "25 дней",
    category: "Уборка",
  },
  {
    id: 14,
    title: "Жатка Shelbourne Reynolds — погрузка в контейнер",
    description: "Очёсывающая жатка Shelbourne Reynolds CVS направляется в 40-футовый контейнер на нашей упаковочной базе, голубая машина эффектно выделяется на фоне стенки контейнера. Деревянные полозья на заказ и стяжные ремни обеспечивают надёжную фиксацию для морского транзита. Груз достиг Одессы, Украина за 24 дня, покупатель интегрировал жатку в свой парк комбайнов John Deere.",
    image: "/images/project-shelbourne-header-load.jpg",
    equipmentType: "Очёсывающая жатка",
    destination: "Одесса, Украина",
    containerType: "40 футов Стандарт",
    weight: "4 800 кг",
    transitTime: "24 дня",
    category: "Уборка",
  },
  {
    id: 12,
    title: "Комбайн John Deere S670 — стоянка в порту",
    description: "Комбайн John Deere S670 ожидает на портовой площадке в Саванне, Джорджия для размещения на flat rack. Жатка была снята и упакована отдельно, выгрузной шнек сложен для габаритного прохождения. Портовый погрузчик готов к финальному позиционированию перед креплением. Комбайн отправлен в Гавр на flat rack Hapag-Lloyd и прибыл за 16 дней без повреждений.",
    image: "/images/project-jd-s670-port.jpg",
    equipmentType: "Зерноуборочный комбайн",
    destination: "Гавр, Франция",
    containerType: "40 футов Flat Rack",
    weight: "14 000 кг",
    transitTime: "16 дней",
    category: "Уборка",
  },
  {
    id: 15,
    title: "Опрыскиватель Hagie — транспортировка на платформе",
    description: "Самоходный опрыскиватель Hagie STS перевозится на низкорамном трале с демонтированными секциями штанги, упакованными в деревянный ящик на заказ с маркировкой покупателя. Опрыскиватель с высоким клиренсом закреплён тяжёлыми цепями и стяжками для наземного перегона из Айовы в порт Хьюстон. Flat rack достиг Марселя за 18 дней.",
    image: "/images/project-hagie-sprayer-flatbed.jpg",
    equipmentType: "Самоходный опрыскиватель",
    destination: "Марсель, Франция",
    containerType: "40 футов Flat Rack",
    weight: "11 000 кг",
    transitTime: "18 дней",
    category: "Опрыскивание",
  },
  {
    id: 21,
    title: "Жатки Shelbourne на трейлере Meridian Freight",
    description: "Несколько очёсывающих жаток Shelbourne Reynolds перевозятся на нашем брендированном трейлере Meridian Freight в Айове, готовые к дальней перевозке в порт. Наш собственный автопарк обеспечивает критическую первую милю — мы сами грузим, крепим и перевозим технику, вместо того чтобы доверять сторонним перевозчикам наиболее рисковый этап. Жатки отправлены в Бишкек через Новороссийск и железную дорогу за 38 дней.",
    image: "/images/project-shelbourne-meridian-trailer.jpg",
    equipmentType: "Очёсывающие жатки",
    destination: "Бишкек, Кыргызстан",
    containerType: "2x 40 футов HC",
    weight: "5 600 кг",
    transitTime: "38 дней",
    category: "Уборка",
  },
  {
    id: 25,
    title: "Сеялка Kinze — зимний вывоз и транспортировка",
    description: "16-рядная сеялка Kinze 3600 буксируется на собственных транспортных колёсах через заснеженные поля Айовы для дальней перевозки в порт. Зимний вывоз требует дополнительного внимания — мы проверили, что высевающие аппараты опорожнены, приводные цепи смазаны, а рядовые секции заблокированы от ударов. Сеялка отправлена из Чикаго через Новороссийск и по железной дороге до Бишкека за 41 день.",
    image: "/images/project-kinze-winter-transport.jpg",
    equipmentType: "Рядковая сеялка",
    destination: "Бишкек, Кыргызстан",
    containerType: "40 футов Flat Rack",
    weight: "6 800 кг",
    transitTime: "41 день",
    category: "Посев",
  },
  {
    id: 19,
    title: "Компактный трактор John Deere 4044R — экспорт на трейлере",
    description: "Мы загрузили компактный универсальный трактор John Deere 4044R с фронтальным погрузчиком на прицеп gooseneck вместе с меньшей газонокосилкой JD zero-turn, закрепив обе единицы тяжёлыми храповыми стяжками. Пакет был консолидирован на нашей базе в Албион перед отправкой в 40-футовом контейнере high-cube. Груз достиг Алматы через порт Актау за 44 дня.",
    image: "/images/project-jd-4044r-tractor.jpg",
    equipmentType: "Компактный трактор",
    destination: "Алматы, Казахстан",
    containerType: "40 футов High Cube",
    weight: "2 400 кг",
    transitTime: "44 дня",
    category: "Тракторы",
  },
  {
    id: 24,
    title: "Жатка MacDon D65 — транспортировка на трейлере",
    description: "Жатка MacDon D65 типа draper перевозится на прицепе gooseneck под пасмурным небом к порту, зубья её подборщикового мотовила силуэтом выделяются на фоне облаков. Полиэтиленовые полозья были обёрнуты защитной плёнкой для предотвращения истирания при перевозке. Груз проследовал через Хьюстон до Актау, затем по железной дороге до Шымкента, достигнув покупателя за 46 дней.",
    image: "/images/project-macdon-d65-draper.jpg",
    equipmentType: "Draper-жатка",
    destination: "Шымкент, Казахстан",
    containerType: "40 футов Flat Rack",
    weight: "3 400 кг",
    transitTime: "46 дней",
    category: "Уборка",
  },
  {
    id: 23,
    title: "Жатка Shelbourne — погрузка в контейнер",
    description: "Очёсывающая жатка Shelbourne Reynolds направляется погрузчиком в 40-футовый контейнер high-cube на нашей базе, голубая машина проходит через проём контейнера с зазором всего в несколько сантиметров с каждой стороны. Позади стоит ещё один flat rack для следующей загрузки. Груз достиг Краснодара, Россия за 34 дня через порт Новороссийск.",
    image: "/images/project-shelbourne-container-load.jpg",
    equipmentType: "Очёсывающая жатка",
    destination: "Краснодар, Россия",
    containerType: "40 футов High Cube",
    weight: "2 700 кг",
    transitTime: "34 дня",
    category: "Уборка",
  },
  {
    id: 22,
    title: "Жатка John Deere 925F — погрузка погрузчиком",
    description: "Погрузчик Toyota заводит жёсткую платформенную жатку John Deere 925F на трейлер на нашей упаковочной базе, рабочие направляют оператора для точной установки. Мотовило жатки было сложено, а разделители сняты для минимизации ширины. Груз достиг Николаева, Украина на flat rack за 26 дней средиземноморским маршрутом, прибыв к началу уборки озимой пшеницы.",
    image: "/images/project-jd-925f-header-load.jpg",
    equipmentType: "Жёсткая платформенная жатка",
    destination: "Николаев, Украина",
    containerType: "40 футов Flat Rack",
    weight: "2 900 кг",
    transitTime: "26 дней",
    category: "Уборка",
  },
  {
    id: 20,
    title: "Жатка John Deere HydraFlex — транспортировка на трейлере",
    description: "Жатка draper John Deere HydraFlex перевозится на низкорамном трейлере в порт, её режущий брус сложен, а мотовило заблокировано в транспортном положении. Деревянные люльки на заказ поддерживают платформу по всей длине для предотвращения прогиба рамы во время транзита. Жатка отправлена в Сантьяго, Чили на flat rack через Панамский канал за 32 дня — одна из первых наших поставок в чилийский пшеничный регион.",
    image: "/images/project-jd-hydraflex-header.jpg",
    equipmentType: "HydraFlex-жатка",
    destination: "Сантьяго, Чили",
    containerType: "40 футов Flat Rack",
    weight: "3 800 кг",
    transitTime: "32 дня",
    category: "Уборка",
  },
];

export const projects: Record<string, Project[]> = {
  en: projectsEn,
  es: projectsEs,
  ru: projectsRu,
};

export function getAllProjects(locale: string = 'en'): Project[] {
  return projects[locale] ?? projects.en;
}

export const projectCategories: Record<string, string[]> = {
  en: ["All", "Harvesting", "Spraying", "Planting", "Tractors", "Parts & Components"],
  es: ["Todos", "Cosecha", "Pulverización", "Siembra", "Tractores", "Repuestos"],
  ru: ["Все", "Уборка", "Опрыскивание", "Посев", "Тракторы", "Запчасти"],
};

export function getProjectCategories(locale: string = 'en'): string[] {
  return projectCategories[locale] ?? projectCategories.en;
}

const equipmentSlugToTypes: Record<string, Record<string, string[]>> = {
  en: {
    combines: ["Combine Harvester", "Combine Harvesters", "Combine Components"],
    tractors: ["Compact Tractor"],
    sprayers: ["Self-Propelled Sprayer"],
    headers: ["Stripper Header", "Stripper Headers", "Draper Header", "HydraFlex Header", "Rigid Platform Header"],
    planters: ["Row Planter", "Air Seeder Cart"],
    bulldozers: [],
    excavators: [],
    loaders: [],
  },
  es: {
    combines: ["Cosechadora", "Cosechadoras", "Componentes de Cosechadora"],
    tractors: ["Tractor Compacto"],
    sprayers: ["Pulverizadora Autopropulsada"],
    headers: ["Cabezal Stripper", "Cabezales Stripper", "Cabezal Draper", "Cabezal HydraFlex", "Cabezal Plataforma Rígida"],
    planters: ["Sembradora de Hileras", "Carro Sembrador"],
    bulldozers: [],
    excavators: [],
    loaders: [],
  },
  ru: {
    combines: ["Зерноуборочный комбайн", "Зерноуборочные комбайны", "Комплектующие комбайна"],
    tractors: ["Компактный трактор"],
    sprayers: ["Самоходный опрыскиватель"],
    headers: ["Очёсывающая жатка", "Очёсывающие жатки", "Draper-жатка", "HydraFlex-жатка", "Жёсткая платформенная жатка"],
    planters: ["Рядковая сеялка", "Посевной бункер"],
    bulldozers: [],
    excavators: [],
    loaders: [],
  },
};

export function getProjectsByEquipmentSlug(
  slug: string,
  locale: string = "en",
  limit: number = 6,
): Project[] {
  const localeMap = equipmentSlugToTypes[locale] ?? equipmentSlugToTypes.en;
  const types = localeMap[slug];
  if (!types || types.length === 0) return [];
  const all = getAllProjects(locale);
  return all.filter((p) => types.includes(p.equipmentType)).slice(0, limit);
}
