import type { LucideIcon } from "lucide-react";
import {
  Wheat,
  Tractor,
  Grip,
  Droplets,
  Sprout,
  Leaf,
  Mountain,
  Package,
  HardHat,
  Hammer,
  Shovel,
  Truck,
  Wrench,
  Layers,
  TreePine,
  TreeDeciduous,
  Axe,
  Container,
  MoreHorizontal,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  combine: Wheat,
  tractor: Tractor,
  header: Grip,
  sprayer: Droplets,
  planter: Sprout,
  seeder: Leaf,
  tillage: Mountain,
  baler: Package,
  construction: HardHat,
  excavator: Shovel,
  wheel_loader: Truck,
  skid_steer: Wrench,
  dozer: Layers,
  forestry: TreePine,
  backhoe: Hammer,
  skidder: TreeDeciduous,
  feller_buncher: Axe,
  forwarder: Container,
  misc: MoreHorizontal,
};
